name: default test
on: 
  push:

jobs:
  veracode:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Veracode UploadAndScan
        uses: bnreplah/veracode-github-action-helper@main
        with:
          action: GetAppList
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}